// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type HTTPHeader struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor"`
	EndCursor       *string `json:"endCursor"`
}

type Webhook struct {
	ID               string          `json:"id"`
	URL              string          `json:"url"`
	Method           HTTPMethod      `json:"method"`
	Headers          []*HTTPHeader   `json:"headers"`
	Body             string          `json:"body"`
	Retries          []*WebhookRetry `json:"retries"`
	Status           WebhookStatus   `json:"status"`
	LatestStatusCode uint            `json:"latestStatusCode"`
	CreatedAt        time.Time       `json:"createdAt"`
	UpdatedAt        time.Time       `json:"updatedAt"`
}

type WebhookConnection struct {
	// A list of nodes.
	Nodes []*Webhook `json:"nodes"`
	// Information to aid in pagination.
	PageInfo *PageInfo `json:"pageInfo"`
	// Identifies the total count of items in the connection.
	TotalCount uint64 `json:"totalCount"`
}

type WebhookRetry struct {
	StatusCode uint      `json:"statusCode"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

type HTTPMethod string

const (
	HTTPMethodGet     HTTPMethod = "GET"
	HTTPMethodPost    HTTPMethod = "POST"
	HTTPMethodPut     HTTPMethod = "PUT"
	HTTPMethodPatch   HTTPMethod = "PATCH"
	HTTPMethodDelete  HTTPMethod = "DELETE"
	HTTPMethodHead    HTTPMethod = "HEAD"
	HTTPMethodOptions HTTPMethod = "OPTIONS"
)

var AllHTTPMethod = []HTTPMethod{
	HTTPMethodGet,
	HTTPMethodPost,
	HTTPMethodPut,
	HTTPMethodPatch,
	HTTPMethodDelete,
	HTTPMethodHead,
	HTTPMethodOptions,
}

func (e HTTPMethod) IsValid() bool {
	switch e {
	case HTTPMethodGet, HTTPMethodPost, HTTPMethodPut, HTTPMethodPatch, HTTPMethodDelete, HTTPMethodHead, HTTPMethodOptions:
		return true
	}
	return false
}

func (e HTTPMethod) String() string {
	return string(e)
}

func (e *HTTPMethod) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = HTTPMethod(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid HttpMethod", str)
	}
	return nil
}

func (e HTTPMethod) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type WebhookStatus string

const (
	WebhookStatusSuccess WebhookStatus = "SUCCESS"
	WebhookStatusFailed  WebhookStatus = "FAILED"
	WebhookStatusExpired WebhookStatus = "EXPIRED"
)

var AllWebhookStatus = []WebhookStatus{
	WebhookStatusSuccess,
	WebhookStatusFailed,
	WebhookStatusExpired,
}

func (e WebhookStatus) IsValid() bool {
	switch e {
	case WebhookStatusSuccess, WebhookStatusFailed, WebhookStatusExpired:
		return true
	}
	return false
}

func (e WebhookStatus) String() string {
	return string(e)
}

func (e *WebhookStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WebhookStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WebhookStatus", str)
	}
	return nil
}

func (e WebhookStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
