// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// CurlHookServiceClient is the client API for CurlHookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CurlHookServiceClient interface {
	Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	Watch(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (CurlHookService_WatchClient, error)
	SendWebhook(ctx context.Context, in *SendWebhookRequest, opts ...grpc.CallOption) (*SendWebhookResponse, error)
}

type curlHookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCurlHookServiceClient(cc grpc.ClientConnInterface) CurlHookServiceClient {
	return &curlHookServiceClient{cc}
}

func (c *curlHookServiceClient) Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/proto.CurlHookService/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *curlHookServiceClient) Watch(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (CurlHookService_WatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &CurlHookService_ServiceDesc.Streams[0], "/proto.CurlHookService/Watch", opts...)
	if err != nil {
		return nil, err
	}
	x := &curlHookServiceWatchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CurlHookService_WatchClient interface {
	Recv() (*HealthCheckResponse, error)
	grpc.ClientStream
}

type curlHookServiceWatchClient struct {
	grpc.ClientStream
}

func (x *curlHookServiceWatchClient) Recv() (*HealthCheckResponse, error) {
	m := new(HealthCheckResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *curlHookServiceClient) SendWebhook(ctx context.Context, in *SendWebhookRequest, opts ...grpc.CallOption) (*SendWebhookResponse, error) {
	out := new(SendWebhookResponse)
	err := c.cc.Invoke(ctx, "/proto.CurlHookService/SendWebhook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CurlHookServiceServer is the server API for CurlHookService service.
// All implementations must embed UnimplementedCurlHookServiceServer
// for forward compatibility
type CurlHookServiceServer interface {
	Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	Watch(*HealthCheckRequest, CurlHookService_WatchServer) error
	SendWebhook(context.Context, *SendWebhookRequest) (*SendWebhookResponse, error)
	mustEmbedUnimplementedCurlHookServiceServer()
}

// UnimplementedCurlHookServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCurlHookServiceServer struct {
}

func (UnimplementedCurlHookServiceServer) Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedCurlHookServiceServer) Watch(*HealthCheckRequest, CurlHookService_WatchServer) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedCurlHookServiceServer) SendWebhook(context.Context, *SendWebhookRequest) (*SendWebhookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendWebhook not implemented")
}
func (UnimplementedCurlHookServiceServer) mustEmbedUnimplementedCurlHookServiceServer() {}

// UnsafeCurlHookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CurlHookServiceServer will
// result in compilation errors.
type UnsafeCurlHookServiceServer interface {
	mustEmbedUnimplementedCurlHookServiceServer()
}

func RegisterCurlHookServiceServer(s grpc.ServiceRegistrar, srv CurlHookServiceServer) {
	s.RegisterService(&CurlHookService_ServiceDesc, srv)
}

func _CurlHookService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurlHookServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CurlHookService/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurlHookServiceServer).Check(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurlHookService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HealthCheckRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CurlHookServiceServer).Watch(m, &curlHookServiceWatchServer{stream})
}

type CurlHookService_WatchServer interface {
	Send(*HealthCheckResponse) error
	grpc.ServerStream
}

type curlHookServiceWatchServer struct {
	grpc.ServerStream
}

func (x *curlHookServiceWatchServer) Send(m *HealthCheckResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CurlHookService_SendWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurlHookServiceServer).SendWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CurlHookService/SendWebhook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurlHookServiceServer).SendWebhook(ctx, req.(*SendWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CurlHookService_ServiceDesc is the grpc.ServiceDesc for CurlHookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CurlHookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CurlHookService",
	HandlerType: (*CurlHookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _CurlHookService_Check_Handler,
		},
		{
			MethodName: "SendWebhook",
			Handler:    _CurlHookService_SendWebhook_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _CurlHookService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service.proto",
}
